apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend
spec:
  selector:
    matchLabels:
      app: em-segmentation
      tier: webapp-frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: em-segmentation
        tier: webapp-frontend
        track: stable
    spec:
      containers:
      - name: webapp-nginx-alpine
        image: 172.31.27.155:5001/webapp/nginx-alpine:v1.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
