apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-nginx
  labels:
    app: webapp-nginx
spec:
  selector:
    matchLabels:
      app: webapp-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-nginx
    spec:
      containers:
      - name: webapp-nginx-alpine
        image: 172.31.24.144:5001/webapp/nginx-alpine:v1.0
        ports:
        - containerPort: 80